### ISSUE TITLE
Test for the Containerfile does not attempt to use skstat/skmanage, misses issues with Proton Python install

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#925]
```
$ docker run --name router -itd --rm quay.io/skupper/skupper-router:main
196e2784d48f4e597cf0057e9daca88d6a88c375d75f62fb98959e935308b6db
$ docker exec router skstat -l
Traceback (most recent call last):
  File "/usr/bin/skstat", line 29, in <module>
    from skupper_router.management.client import Node
  File "/usr/lib/python3.9/site-packages/skupper_router/management/client.py", line 22, in <module>
    import proton
ModuleNotFoundError: No module named 'proton'
```

Reported by @fgiorgetti

**Comment by ganeshmurthy** [comment]
@jiridanek this issue seems to have been fixed by you already. Close this issue ?

**Comment by jiridanek** [comment]
@ganeshmurthy The job still does not check that skstat/skmanage run, so there is more work to do. (They do run now, but it is not tested there.)

**Comment by jiridanek** [comment]
One additional problem; the test does not wait for router to start and open port, so if it starts slowly, test fails. This is also something to be solved here.

See HEALTHCHECK Containerfile instruction, https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/assembly_monitoring-containers_building-running-and-managing-containers#performing-a-health-check-using-a-containerfile_assembly_monitoring-containers

Healthcheck feature is present in the router, https://github.com/skupperproject/skupper-router/commit/1e22255eede6f82828a433839cb25087c2c7b300 hopefully it does what I need it to do (claim Healthy only when all listeners declared in config were opened).
